### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by HXM4Tech** [FuzionCoin-dev/py-fuzioncoin#1]
I'm publishing a roadmap to lay out the path we'll follow in PyFuzc development. This roadmap is also intended to help volunteers contribute to the project.

- [x] Server and client
- [x] Connection handler (to handle connections, given by server and client)
- [x] Protocol basic messaging system (JSON)
- [x] Basic welcome messages handler
- [x] Configuration file support
- [x] Logger (to show info about what's going on in stdout and save it to log file)
- [x] Transaction, Block and Blockchain classes
- [ ] Wallet adresses
- [ ] Coinbase class (with a supply limit of FUZC 10,000,000)
- [ ] Protocol GetHeight, Inv, GetBlock and GetTx methods
- [ ] Synchronizing node with the network on start
- [ ] Creating transactions and announcing them in network
- [ ] Validating transactions, adding them to block, minning blocks, announcing blocks in network
- [ ] Other protocol methods
- [ ] Blocks reward
[...]
